# .github/actions/extract-rpm/action.yml
name: Extract RPM
description: Extracts a .src.rpm and generates a FOSSA deps file

inputs:
  rpm_name:
    required: true
  dependency_name:
    required: true
  version:
    required: true
  output_path:
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        set -euo pipefail

        echo "Extracting ${{ inputs.rpm_name }} into ${{ inputs.output_path }}"
        mkdir -p "${{ inputs.output_path }}"
        cp "${{ inputs.rpm_name }}" .

        FILE_SIZE=$(stat -c%s "${{ inputs.rpm_name }}")
        echo "RPM file size: $FILE_SIZE bytes ($(numfmt --to=iec $FILE_SIZE))"

        cd "${{ inputs.output_path }}"

        if [ "$FILE_SIZE" -gt 4294967296 ]; then
          7z x "../${{ inputs.rpm_name }}" -y
          [ -f *.cpio.gz ] && gunzip *.cpio.gz
          [ -f *.cpio.xz ] && xz -d *.cpio.xz
          [ -f *.cpio ] && 7z x *.cpio -y || true
        else
          rpm2cpio "../${{ inputs.rpm_name }}" | cpio -idmv
        fi

        echo "Writing fossa-deps.yml..."
        cat > ../../fossa-deps.yml <<EOF
vendored-dependencies:
  - name: ${{ inputs.dependency_name }}
    version: "${{ inputs.version }}"
    path: "${{ inputs.output_path }}/"
EOF
